# app/agent/workflows/node_persistence.py

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from app.agent.context.graph_traversal import GraphTraversal
from app.core.model.schemas import DocumentSchema
from app.db.async_terminus_client import WOQLQuery as WQ

try:
    from terminusdb_client.woqlquery.woql_query import Doc
except ImportError:  # pragma: no cover
    Doc = dict  # type: ignore

logger = logging.getLogger(__name__)


class NodePersistence:
    """
    All DB write operations for workflows.

    Keeps workflow classes focused on orchestration + LLM calls.
    """

    def __init__(self, graph: GraphTraversal):
        self._graph = graph

    @property
    def _client(self):
        return self._graph.repos.client

    # -- descriptions -----------------------------------------------------

    async def flush_descriptions(
        self,
        node_updates: dict[str, Any],
    ) -> None:
        if not self._client or not node_updates:
            return

        for node in node_updates.values():
            node_id = getattr(node, "id", None)
            if not node_id:
                continue

            queries = []
            if hasattr(node, "description"):
                queries.extend(
                    [
                        WQ().opt(
                            WQ()
                            .triple(
                                node_id,
                                "description",
                                "v:old_description",
                            )
                            .delete_triple(
                                node_id,
                                "description",
                                "v:old_description",
                            )
                        ),
                        WQ().add_triple(
                            node_id,
                            "description",
                            WQ().string(
                                getattr(node, "description", "") or ""
                            ),
                        ),
                    ]
                )

            if hasattr(node, "documents"):
                for doc_id in set(getattr(node, "documents") or set()):
                    queries.append(
                        WQ().opt(
                            WQ().add_triple(
                                node_id, "documents", doc_id
                            )
                        )
                    )

            if queries:
                await self._client.query(
                    WQ().woql_and(*queries),
                    commit_msg=f"Workflow: update node {node_id}",
                )

    # -- documentation documents ------------------------------------------

    @staticmethod
    def documentation_doc_id(node_id: str) -> str:
        safe = node_id.replace("/", "_").replace(":", "_")
        return f"DocumentSchema/{safe}_workflow_documentation"

    async def flush_documentation_batch(
        self,
        documentation_values: dict[str, str],
        processed_nodes: dict[str, Any],
    ) -> list[str]:
        if not self._client or not documentation_values:
            return []

        now = datetime.now(timezone.utc)
        doc_ids = [
            self.documentation_doc_id(nid)
            for nid in documentation_values
        ]

        existing_docs: dict[str, dict] = {}
        try:
            existing = await self._client.get_documents(doc_ids)
            existing_docs = {
                doc.get("@id"): doc for doc in existing
            }
        except Exception:
            existing_docs = {}

        document_queries = []
        link_queries = []

        for node_id, content in documentation_values.items():
            doc_id = self.documentation_doc_id(node_id)
            created_at = existing_docs.get(doc_id, {}).get(
                "created_at", now
            )

            schema = DocumentSchema(
                _id=doc_id,
                name=f"workflow_doc:{node_id}",
                description="Generated by documentation workflow.",
                data=content,
                created_at=created_at,
                updated_at=now,
            )
            document_queries.append(
                WQ().insert_document(Doc(schema._obj_to_dict()[0]))
            )

            tree_node = processed_nodes.get(node_id)
            tree_node_id = (
                getattr(tree_node, "id", None)
                if tree_node
                else None
            )
            if tree_node_id:
                link_queries.append(
                    WQ().opt(
                        WQ().add_triple(
                            tree_node_id, "documents", doc_id
                        )
                    )
                )

        if document_queries:
            await self._client.query(
                WQ().woql_and(*document_queries),
                commit_msg=(
                    f"Workflow: upsert {len(document_queries)} "
                    "generated documents"
                ),
            )
        if link_queries:
            await self._client.query(
                WQ().woql_and(*link_queries),
                commit_msg=(
                    f"Workflow: link {len(link_queries)} "
                    "documents to nodes"
                ),
            )

        return doc_ids

    async def check_document_exists(self, node_id: str) -> bool:
        if not self._client:
            return False
        doc_id = self.documentation_doc_id(node_id)
        try:
            existing = await self._client.get_documents([doc_id])
            return bool(
                existing and (existing[0].get("data") or "").strip()
            )
        except Exception:
            return False
